[build]
  publish = ".next"
  command = "npm ci && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NETLIFY_SKIP_BUILD_CACHE = "true"

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
